---
title: "pogRomcy 1.2"
author: "Przemyslaw Lagosz"
date: "18-03-2021"
output: html_document
---
# Odczytywanie, zapisywanie i indeksowanie danych  

```{r Ustawienie opcji globalnych}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## 5. Jak wczytać dane do R  

```{r Jak wczytać dane do R}

#Opis pakietu

data(package="PogromcyDanych")

library(PogromcyDanych)

#wczytanie biblioteki z read.xls

library(gdata)

###################################### ZADANIA ###########################################

read.table(file = "http://biecek.pl/MOOC/dane/koty_ptaki.csv", 
           sep=";", dec=",", header=TRUE)

auta <- read.xls("http://biecek.pl/MOOC/dane/auta2012mini.xls", sheet = 1)

autacsv <- read.csv("http://biecek.pl/MOOC/dane/auta2012mini.csv", sep= ";", dec = '.', header = T)

load(url("http://biecek.pl/MOOC/dane/auta2012mini.rda"))


```

## 6. Jak zapisać dane z R  

```{r Jak zapisać dane z R, eval=FALSE}
dwie_kolumny <- data.frame(litery = c("A", 'B', 'C'),
                           liczby = c('1', '2', '3'))

## write.table(dwie_kolumny, file = "wazne_dane.csv", sep = ";", dec = ".")

#install.packages("xlsx")

library(xlsx)

#zapisuje do excela, wymagana Java

## write.xlsx(dwie_kolumny, file = "wazne_dane.xlsx", sheetName = "Zakladka Wazne Dane")

#zapisanie w formacie natywnym

## save(dwie_kolumny, file = "Wazne_dane.rda")

#tworzy wektor z literami

l1 <- LETTERS[1:10]

###################################### ZADANIA ###########################################

library(PogromcyDanych)

# Zapisz zbiór danych koty_ptaki do pliku tekstowego, w którym dane są rozdzielane przecinkiem a separatorem dziesiętnym jest . (kropka).

## write.table(koty_ptaki, 
##            file = 'C:/R/Pogromcy Danych/Pogromcy/koty_ptaki.csv', 
##            sep = ",", 
##            dec = ".")

# Zapisz zbiór danych koty_ptaki do formatu pliku Excela. Sprawdź czy dane poprawnie się zapisały.

##write.xlsx(koty_ptaki, file ="koty_ptaki.xlsx", 
##           sheetName = "Koty Ptaki")

# Zapisz zbiór danych koty_ptaki do pliku binarnego. Odczytaj go następnie funkcją load() i 
# sprawdź czy dane poprawnie zostały zapisane.

## save(koty_ptaki, file = "koty_ptaki.rda")

## load(file = "koty_ptaki.rda")
```

## 7. Indeksowanie wektorów i ramek danych  

```{r Indeksowanie wektorów i ramek danych}
LETTERS

LETTERS > "K"

LETTERS[LETTERS > "K"]

#Zbuduj sekwencj? dziesi?ciu kolejnych ma?ych liter alfabetu ?aci?skiego.

pierwsze_10 <- LETTERS[1:10]

pierwsze_10
#Zbuduj sekwencje dziesięciu kolejnych liczb nieparzystych zaczynaj?c od 3.

nieparzyste <- seq(from = 3, by = 2, length.out = 10)

#Z wektora LETTERS wybierz litery na pozycjach 5, 10, 15, 20 i 25.

co5 <- LETTERS[seq(from = 5, by = 5, to = 25)]

#Wypisz wartosci wektora LETTERS od ko?ca.

odtylca <- LETTERS[length(LETTERS):1]


nrow(koty_ptaki)
ncol(koty_ptaki)
koty_ptaki[2,3]

# Tworzy wektor T/F jeśli warunek jest spełniony, nastepnie ten wektor używty do indeksowania
najszybsze <- koty_ptaki$predkosc > 100
najszybsze

koty_ptaki[najszybsze, ]

# Tworzy wektor sample z o dlugosci `nrow(koty_ptaki)`, `prob` określa stosunek

sample <- sample(c("TRUE","DUPA"), size = nrow(koty_ptaki), replace = T, prob = c(0.1, 0.9))

# Tworzy wektor z ujemnymi wartosciami
-c(1:5)   
koty_ptaki[-1:-5,]
koty_ptaki[-c(1:5),]

#wybiera kolumne predkosc, przeksztalca na wektor
koty_ptaki[,"predkosc"]

#wybiera kolumne predkosc, NIE przeksztalca na wektor
koty_ptaki[,"predkosc", drop = F]

kolumny <- colnames(koty_ptaki)
kolumny[1:3]

# Przypisuje pod nazwy wierzy garunki

rownames(koty_ptaki) <- koty_ptaki$gatunek

# Wyrzuca INDEKSY w kolejność rosnącej/malejącej

order(koty_ptaki[,'predkosc'])

# Przypisuje pod koty_ptaki posortowane koty_ptaki według kolumny "predkość"

koty_ptaki <- koty_ptaki %>%
  arrange(predkosc)

###################################### ZADANIA ###########################################

#Wybierz z ramki danych koty_ptaki wszystkie wiersze poza "Sokołami" (wiersz 11 i 12).

wektor <- 1:nrow(koty_ptaki)

rownames(koty_ptaki) <- wektor

nrow(koty_ptaki)

koty_ptaki[-c(8,9), ]


# Wybierz z ramki danych koty_ptaki tylko koty (pierwsze siedem wierszy).

koty_tylko <- koty_ptaki %>%
  filter(druzyna == "Kot")

koty_ptaki[koty_ptaki$druzyna == "Kot", ]

# Wybierz z ramki danych koty_ptaki tylko kolumnę z wagą i prędkością.

koty_ptaki[,c("waga","predkosc"), drop=F]

# Wybierz z ramki danych koty_ptaki wszystkie kolumny poza ostatnią.

koty_ptaki[,-ncol(koty_ptaki)]

# Wybierz z ramki wiersze dla których waga jest mniejsza niż 100 oraz cztery pierwsze kolumny.

lekkie <- koty_ptaki$waga < 100
koty_ptaki[lekkie, 1:4]

koty_ptaki[koty_ptaki$waga < 100, 1:4]
```